---
title: "Treelife demo"
author: "Jaideep Joshi"
date: "2023-01-21"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
library(PlantFATE)
library(tidyverse)
library(kableExtra)

print(getwd())
```

```{r}
# Function to preview tables using kable
preview_table <- function(data, n=6) {
  data |> 
    head(n=n) |> 
    kable() |> 
    kable_styling() |> 
    column_spec(1:ncol(data), border_left = "solid lightgray", border_right = "solid lightgray") |> 
    scroll_box(width = "100%")
}

plot_gauss_mix = function(x, means, sds, wts, add=T, col, add_polygon=F, ...){
  y = x*0
  if (length(sds)==1) sds = rep(sds, length(means))
  for (i in 1:length(means)){
    y = y + wts[i]*dnorm(x, mean = means[i], sd=sds[i])
  }
  if (add) points(y~x, col=col, ...)
  else plot(y~x, col=col, ...)
  if (add_polygon){
    polygon(y~x, col=scales::alpha(col, 0.5), border = NA)
  }
}
```

## Analyze observed traits

```{r}
traits = read_csv("input_data/Plant_Traits_AmzFACE_for_PlantFATE_Orig.csv")

traits |> preview_table()
```


Plot observed distributions

```{r}

par(mfrow=c(2,2), mar=c(4,4,1,1), oma=c(1,1,1,1))
traits |> 
    select(Species, BA='Total BasalArea_2017(cm2)', WD='meanWoodDensity (g/cm3)', Hmat='Height_Max(m)', LMA='Leaf LMA (g/m2)', P50='P50 (Mpa)') |> 
    pivot_longer(-c(Species, BA)) |> 
    drop_na() |>
    group_by(name) |> 
    do(
        with(., 
          plot_gauss_mix(
            x=seq(min(value), max(value), length.out=100), 
            means=value, 
            sds=0.14*mean(abs(value), na.rm=T), 
            wts=BA/sum(BA), 
            add=F, 
            col="blue", 
            type="l",
            add_polygon=F,
            xlab=first(name),
            ylab = "Density"
          ) |> as.data.frame()
        )
    )
```


Calculate basal-area weighted mean traits from the observed data

```{r}
mean_traits = traits |> 
    select(Species, BA='Total BasalArea_2017(cm2)', WD='meanWoodDensity (g/cm3)', Hmat='Height_Max(m)', LMA='Leaf LMA (g/m2)', P50='P50 (Mpa)') |> 
    pivot_longer(-c(Species, BA)) |> 
    drop_na() |>
    group_by(name) |> 
    summarize(mean = sum(value*BA)/sum(BA),
              sd = sqrt(sum(BA*(value - mean(value))^2)/sum(BA)),
              n = n(),
              cv = sd/abs(mean),
              cv2 = cv^2)

mean_traits |> preview_table()

mt_wide = mean_traits |> 
    select(name, mean) |>
    pivot_wider(values_from = mean) |> 
    mutate(LMA = LMA/1000,
           WD = WD*1000) 
```

## Optimal traits

Now we will find the optimal traits for the given light environment

```{r}
input_dir = "input_data"
output_dir = "pfate_output"
prefix = "AmzMIP_AMB_ObsMeanTraits"
solver = "ebt"
dir = paste0("",output_dir,"/",prefix,"_",solver)

l = pf_read_outputs(input_dir, output_dir, expt_dir=prefix)

zstar = l$Zp |>
  filter(YEAR > (max(YEAR)-100)) |>
  summarize(across(everything(), ~mean(.x, na.rm = TRUE))) |> 
  pivot_longer(-YEAR) |>
  drop_na() |> 
  pull(value)
  
canopy_opennes = l$co |>
  filter(YEAR > (max(YEAR)-100)) |>
  summarize(across(everything(), ~mean(.x, na.rm = TRUE))) |> 
  pivot_longer(-YEAR) |>
  drop_na() |> 
  pull(value)

zstar |> 
  print()

canopy_opennes |> 
  print()
```

## Run the life history of a given species

```{r echo=F}
plot_plant_trajectory = function(dat){
  dat$leaf_area = dat$crown_area * dat$lai
  dat$heartwood_fraction = 1-dat$sapwood_fraction
  
  # par(mfrow=c(4,2), mar=c(4,4,1,1), oma=c(1,1,1,1))
  
  # plot(dat$height~dat$diameter, type="l", ylab="Height", xlab="Diameter")
  # plot(dat$crown_area~I(dat$height*dat$diameter), type="l", ylab="Crown area", xlab="DH")
  # plot(I(dat$total_rep/dat$total_prod)~dat$height, type="l", ylab="Frac alloc to\nreproduction", xlab="Height")
  # plot(I(dat$total_rep/dat$total_prod)~dat$diameter, type="l", ylab="Frac alloc to\nreproduction", xlab="Diameter")
  
  par(mfrow=c(4,4), mar=c(4,8,1,1), oma=c(1,1,1,1), mgp=c(4,1,0), cex.lab=1.2)
  
  plot(dat$height~dat$i, ylab="Height", xlab="Year", type="l", lwd=2)
  plot(dat$diameter~dat$i, ylab="Diameter", xlab="Year", col="brown", type="l", lwd=2)
  
  matplot(y=cbind(dat$total_mass,
                  dat$total_rep,
                  dat$litter_mass,
                  dat$total_mass+dat$total_rep+dat$litter_mass,
                  dat$total_prod), 
          x=dat$i, col=c("green4", "purple", "yellow4", "black", "red"), log="", lty=c(1,1,1,1,2), lwd=c(1,1,1,2,1), type="l",
          ylab="Biomass pools", xlab="Year")
  abline(h=0, col="grey")
  
  matplot(y=cbind(dat$total_mass,
                  dat$leaf_mass,
                  dat$root_mass,
                  dat$coarse_root_mass,
                  dat$stem_mass),
          x=dat$i, col=c("black", "green3", "purple", "purple3", "brown"), log="", lty=c(1,1,1,1,1), lwd=c(1,1,1,1,1), type="l",
          ylab="Biomass pools", xlab="Year")
  abline(h=0, col="grey")
  
  
  matplot(y=cbind(dat$fitness), 
          x=dat$i, col=c("purple2", "magenta", "pink"), log="", lty=c(1,1,1), lwd=c(1,1,2), type="l",
          ylab="Fitness", xlab="Year")
  abline(h=0, col="grey")
  
  # plot(dat$total_mass~dat$i, ylab="Total biomass", xlab="Year")
  # plot(dat$total_mass~dat$i, ylab="Total biomass", xlab="Year")
  # 
  # points(y=dat$total_prod-dat$litter_mass, x=dat$i, type="l", col="red")
  
  # plot(y=1 - (dat$total_prod-dat$litter_mass)/dat$total_mass, x=dat$i, ylab="Total biomass", xlab="Year")
  
  # plot(dat$ppfd[01:1000]~dat$i[01:1000], type="l")
  # plot(dat$assim_gross[901:1000]~dat$ppfd[901:1000], type="l")
  
  
  matplot(y=cbind(dat$assim_gross/dat$crown_area,
                  dat$assim_net/dat$crown_area,
                  dat$assim_net/dat$assim_gross * max(dat$assim_gross/dat$crown_area)), 
                  x=dat$i, col=c("green3", "green4", scales::alpha("yellow3", 0.5)), log="", lty=1, type="l", lwd=c(1,1,3),
                  ylab=expression(atop("GPP, NPP", "(kg m"^"-2"*"Yr"^"-1"*")")), xlab="Year")
  abline(h=0, col="grey")
  
  matplot(y=cbind(dat$rr/dat$crown_area,
                  dat$rs/dat$crown_area,
                  dat$rl/dat$crown_area), 
                  x=dat$i, col=c("pink2", "pink3", "pink4"), log="", lty=1, type="l",
                  ylab="Respiration", xlab="Year")
  
  matplot(y=cbind(dat$tr/dat$crown_area,
                  dat$tl/dat$crown_area), 
                  x=dat$i, col=c("orange3", "orange4"), log="", lty=1, type="l",
                  ylab="Turnover", xlab="Year",
                  add=F)
  
  plot(I(dat$transpiration/dat$crown_area/1000*1000)~dat$i, type="l", col="blue", ylab="Transpitation\n(mm/yr)")
  
  plot(dat$dpsi~dat$i, type="l", col="cyan", ylab=expression(atop(Delta*psi, "(MPa)")), xlab="Year")
  
  plot(dat$vcmax~dat$i, type="l", col="limegreen", ylab=expression(atop(V[cmax], "("*mu*"mol m"^"-2"*"s"^"-1"*")")), xlab="Year")
  
  plot(I(dat$leaf_area/dat$crown_area)~dat$i, ylab="LAI", xlab="Year", type="l")
  
  plot(I(dat$mortality)~dat$i, ylab="Cumulative\nMortality", xlab="Year", type="l")
  
  # Instantaneous mortality
  dat %>% filter(diameter<0.5) %>% 
    select(diameter, 
              mortrate_0, 
              mortrate_growth, 
              mortrate_d, 
              mortrate_hyd, 
              mortality_inst) %>% 
    with(matplot(y=.[,-1], x=.[,1], ylab="Instantaneous\nmortality rate", xlab="Diameter", type="l", lty=1, 
       col=c("yellow3", 
             "green3", 
             "brown", 
             "blue", 
             "black")))
  
  matplot(y=cbind(dat$sapwood_fraction, 
                dat$heartwood_fraction),
          x=dat$i, 
          ylab="Sap/Heart wood\nfraction", xlab="Year", type="l", col=c("yellowgreen", "brown4"), lty=1, lwd=1)
  
  # plot(I(dat$ppfd)~dat$i, ylab="PPFD", xlab="Year", type="l", col="yellowgreen")
  
  matplot(y=(cbind(dat$leaf_lifespan, 
                  dat$fineroot_lifespan)),
          x=dat$height, 
          ylab="Leaf/fine root\nlifespan", xlab="Height", type="l", col=c("yellowgreen", "brown4"), lty=1, lwd=1)
}
```

```{r}
config_file = "config_files/p_amz_obs_mean_traits_sapwoodresp_newmort.ini"

lho = new(LifeHistoryOptimizer, config_file)
lho$init()
lho$printMeta()

dt = 0.1
df = read.csv(text="", col.names = lho$get_header())
for (t in seq(2000,2500,dt)){
  lho$grow_for_dt(t,0.1)
  df[nrow(df)+1,] = lho$get_state(t+dt)
}

plot_plant_trajectory(df)

# plot mortality specifically
par(mfrow=c(1,1))
df %>% filter(diameter<0.5) %>% 
  select(diameter, 
            mortrate_0, 
            mortrate_growth, 
            mortrate_d, 
            mortrate_hyd, 
            mortality_inst) %>% 
  with(matplot(y=.[,-1], x=.[,1], ylab="Instantaneous\nmortality rate", xlab="Diameter", type="l", lty=1, 
     col=c("yellow3", 
           "green3", 
           "brown", 
           "blue", 
           "black")))

# lho$calcFitness()
```

## Compute fitness landscape

```{r}
fitness_wd = function(wd, p50, lma, hmat, zp, co, co2, zeta, mgamma = 0.0094, minf=0, pfile=config_file){
  lho = new(LifeHistoryOptimizer, pfile)
  lho$set_i_metFile("input_data/MetData_AmzFACE_Monthly_2000_2015_PlantFATE_new.csv")
  lho$set_a_metFile("input_data/MetData_AmzFACE_Monthly_2000_2015_PlantFATE_new.csv")
  lho$init_co2(co2)
  lho$env$z_star = zp
  lho$env$canopy_openness = co
  lho$traits0$wood_density = wd
  lho$traits0$p50_xylem = p50
  lho$traits0$hmat = hmat
  lho$traits0$lma = lma
  lho$traits0$zeta = zeta
  lho$par0$m_gamma = mgamma
  lho$par0$m_inf = minf

  lho$init()
  # lho$printPlant()
  lho$calcFitness(1500, 2000)
}

wd = seq(400, 900, length.out=20)

library(furrr)
plan(multisession, workers = 6)

wd_scan = tibble(
  wd=wd, 

  dat_wd_def = wd %>% furrr::future_map_dbl(.f = fitness_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=368, zeta=0.2),

  dat_wd_zetaplus = wd %>% furrr::future_map_dbl(.f = fitness_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=368, zeta=0.3),

  dat_wd_co2plus = wd %>% furrr::future_map_dbl(.f = fitness_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=614, zeta=0.2),

  dat_wd_mplus = wd %>% furrr::future_map_dbl(.f = fitness_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=368, zeta=0.2, mgamma = 0.02),

  dat_wd_minf = wd %>% furrr::future_map_dbl(.f = fitness_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=368, zeta=0.2, minf = 0.005)
)


print(
wd_scan |> 
  ggplot(aes(x=wd)) +
  geom_line(aes(y=dat_wd_def/max(dat_wd_def)), col="blue") +
  geom_line(aes(y=dat_wd_zetaplus/max(dat_wd_zetaplus)), col="brown") +
  geom_line(aes(y=dat_wd_co2plus/max(dat_wd_co2plus)), col="green3") +
  geom_line(aes(y=dat_wd_mplus/max(dat_wd_mplus)), col="orange3") +
  geom_line(aes(y=dat_wd_minf/max(dat_wd_minf)), col="black") +
  labs(x="Wood Density (g/cm3)", y="Fitness") +
  theme_classic(base_size = 16)
)

p50 = seq(-4, -1, length.out=20)

dat_p50 = p50 %>% furrr::future_map_dbl(.f = fitness_wd, wd=mt_wide$WD, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=368, zeta=0.2)

print(
tibble(p50=p50, fitness=dat_p50) |> 
  ggplot(aes(x=p50, y=fitness)) +
  geom_line() +
  labs(x="Xylem P50 (MPa)", y="Fitness") +
  theme_classic(base_size = 16)
)

```

```{r}
opt_wd = function(minf, p50, lma, hmat, zp, co, co2, zeta, mgamma, pfile=config_file){

  wd = seq(400, 900, length.out=20)

  fit = wd %>% furrr::future_map_dbl(.f = fitness_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=co2, zeta=zeta, mgamma=mgamma, minf=minf, pfile=pfile)

  wd[fit == max(fit)]
}


## Optimal WD as a function of Minf

wd_opt_minf = tibble(minf = exp(seq(log(0.001), log(0.01), length.out=10)),
       wd_opt = minf %>% furrr::future_map_dbl(.f = opt_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=368, zeta=0.2, mgamma=0.0094)
       ) 

wd_opt_minf %>% 
     ggplot(aes(x=minf, y=wd_opt))+
     geom_point()+
    geom_smooth()


## Optimal WD as a function of zeta

wd_opt_zeta = tibble(zeta = seq(0.1, 0.3, length.out=10),
       wd_opt = zeta %>% furrr::future_map_dbl(.f = opt_wd, p50=mt_wide$P50, hmat=mt_wide$Hmat, lma=mt_wide$LMA, zp=zstar, co=canopy_opennes, co2=368, mgamma=0.0094, minf = 0)
       ) 

wd_opt_zeta %>% 
     ggplot(aes(x=zeta, y=wd_opt))+
     geom_point()+
    geom_smooth()


```
